import type { Locale } from "@/i18n/strings"

const en = {
  cancel: "Cancel",
  dashboard: "Your daily playbook.",
  subtitle: "PLAY. RECORD. REPEAT.",
  input: "Every game. One place.",
  inputHint: "Paste the share text from your games. Results are saved automatically.",
  local: "Saved on this device",
  ticket: "GAME RECORD",
  won: "Completed",
  lost: "Not completed",
  attempts: "Attempts",
  edition: "Edition",
  date: "Date",
  points: "Points",
  modes: "Modes",
  manual: "Manual loss",
  result: "Result",
  hints: "Hints",
  round: "Round",
  streak: "Streak",
  grid: "Result grid",
  close: "Close",
  catalog: "Design system",
}
type Copy = { [K in keyof typeof en]: string }
export const industrialCopy: Record<Locale, Copy> = {
  en,
  "pt-BR": {
    cancel: "Cancelar",
    dashboard: "Seu diário de jogos.",
    subtitle: "JOGUE. REGISTRE. REPITA.",
    input: "Cada jogo. Um só lugar.",
    inputHint: "Cole o texto compartilhado pelos jogos. Os resultados são salvos automaticamente.",
    local: "Salvo neste dispositivo",
    ticket: "REGISTRO DE JOGO",
    won: "Concluído",
    lost: "Não concluído",
    attempts: "Tentativas",
    edition: "Edição",
    date: "Data",
    points: "Pontos",
    modes: "Modos",
    manual: "Derrota manual",
    result: "Resultado",
    hints: "Dicas",
    round: "Rodada",
    streak: "Sequência",
    grid: "Grade do resultado",
    close: "Fechar",
    catalog: "Design system",
  },
}
