"""Refresh the small, locally hosted font set and its licenses."""
from pathlib import Path
import re
import subprocess
from urllib.request import Request, urlopen

ROOT = Path(__file__).resolve().parents[1]
DEST = ROOT / "public/fonts"
DEST.mkdir(exist_ok=True)
UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36"


def fetch(url):
    with urlopen(Request(url, headers={"User-Agent": UA}), timeout=60) as response:
        return response.read()


families = [
    ("archivo", "Archivo:wght@400;600;700"),
    ("chakrapetch", "Chakra+Petch:wght@500;700"),
    ("splinesansmono", "Spline+Sans+Mono:wght@400;500"),
    ("notosansjp", "Noto+Sans+JP:wght@700&text=%E3%83%9F%E3%83%8B%E3%82%B2%E3%83%BC%E3%83%A0"),
]
rules = ["/* Generated by scripts/fetch_fonts.py. Licenses: public/fonts/*-OFL.txt. */"]
assets = {}
for slug, query in families:
    css = fetch(f"https://fonts.googleapis.com/css2?family={query}&display=swap").decode()
    for index, (subset, block) in enumerate(re.findall(r"(?:/\*\s*(.*?)\s*\*/\s*)?(@font-face\s*\{.*?\})", css, re.S)):
        if slug != "notosansjp" and subset not in ("latin", "latin-ext", ""):
            continue
        match = re.search(r"url\((https://[^)]+)\)", block)
        if not match:
            continue
        url = match[1]
        ext = ".woff2" if "woff2" in block else ".woff"
        filename = assets.get(url, f"{slug}-{index}{ext}")
        if url not in assets:
            (DEST / filename).write_bytes(fetch(url))
            assets[url] = filename
        rules.append(block.replace(url, f"/fonts/{filename}").replace("'", '"'))
    license_url = f"https://raw.githubusercontent.com/google/fonts/main/ofl/{slug}/OFL.txt"
    license_text = fetch(license_url).decode("utf-8")
    (DEST / f"{slug}-OFL.txt").write_text(
        "\n".join(line.rstrip() for line in license_text.splitlines()) + "\n",
        encoding="utf-8",
    )
    print(f"Saved {slug}")
css_path = ROOT / "src/design-system/fonts.css"
css_path.write_text("\n\n".join(rules) + "\n", encoding="utf-8")
subprocess.run(
    ["bun", "x", "biome", "format", "--write", str(css_path)],
    cwd=ROOT,
    check=True,
)
